spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_DATABASE}?characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

user:
  sys:
    role: SYSTEM
    id: ${SYS_USER_ID}

sse:
  timeout: 1800000