spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_DATABASE}?characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver

sse:
  timeout: 1800000